/**
 *
 * $Id$
 */
package SimpleRequirementMM.validation;

import SimpleRequirementMM.Requirement;
import SimpleRequirementMM.RequirementLevel;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SimpleRequirementMM.RequirementLevel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RequirementLevelValidator {
	boolean validate();

	boolean validateOwnedLevel(EList<RequirementLevel> value);
	boolean validateOwnedRequirement(EList<Requirement> value);
}
